=begin
PIER Labs


Gest\u00E3o de pagamento eletr\u00F4nicos como servi\u00E7o


OpenAPI spec version: 0.0.1
Contact: pierlabs@conductor.com.br
Generated by: https://github.com/swagger-api/swagger-codegen.git


License: Apache 2.0
http://www.apache.org/licenses/LICENSE-2.0.html



Terms of Service: http://pierlabs.io/terms/


=end

require 'date'

module Pier
  # {{{configuracao_rotativo_detalhe_response_description}}}
  class ConfiguracaoRotativoDetalheResponse
    # {{{configuracao_rotativo_detalhe_response_id_value}}}
    attr_accessor :id

    # {{{configuracao_rotativo_detalhe_response_id_produto_value}}}
    attr_accessor :id_produto

    # {{{configuracao_rotativo_detalhe_response_compoe_oferta_valor_rotativo_value}}}
    attr_accessor :compoe_oferta_valor_rotativo

    # {{{configuracao_rotativo_detalhe_response_compoe_oferta_valor_nao_financiavel_value}}}
    attr_accessor :compoe_oferta_valor_nao_financiavel

    # {{{configuracao_rotativo_detalhe_response_compoe_oferta_valor_novos_lancamentos_value}}}
    attr_accessor :compoe_oferta_valor_novos_lancamentos

    # {{{configuracao_rotativo_detalhe_response_recalcula_parcelamento_para_entrada_maior_value}}}
    attr_accessor :recalcula_parcelamento_para_entrada_maior

    # {{{configuracao_rotativo_detalhe_response_minimo_parcelas_recalculo_parcelamento_value}}}
    attr_accessor :minimo_parcelas_recalculo_parcelamento

    # {{{configuracao_rotativo_detalhe_response_recalcula_parcelamento_value}}}
    attr_accessor :recalcula_parcelamento

    # {{{configuracao_rotativo_detalhe_response_numero_minimo_ofertas_value}}}
    attr_accessor :numero_minimo_ofertas

    # {{{configuracao_rotativo_detalhe_response_aceita_pagamento_maior_que_entrada_value}}}
    attr_accessor :aceita_pagamento_maior_que_entrada

    # {{{configuracao_rotativo_detalhe_response_antecipa_parcelamentos_abertos_value}}}
    attr_accessor :antecipa_parcelamentos_abertos

    # {{{configuracao_rotativo_detalhe_response_valor_minimo_parcela_value}}}
    attr_accessor :valor_minimo_parcela

    # {{{configuracao_rotativo_detalhe_response_percentual_limitar_valor_minimo_parcela_value}}}
    attr_accessor :percentual_limitar_valor_minimo_parcela

    # {{{configuracao_rotativo_detalhe_response_id_regra_campanha_value}}}
    attr_accessor :id_regra_campanha

    # {{{configuracao_rotativo_detalhe_response_parcelar_apenas_minimo_value}}}
    attr_accessor :parcelar_apenas_minimo

    # {{{configuracao_rotativo_detalhe_response_usuario_value}}}
    attr_accessor :usuario


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'id' => :'id',
        
        :'id_produto' => :'idProduto',
        
        :'compoe_oferta_valor_rotativo' => :'compoeOfertaValorRotativo',
        
        :'compoe_oferta_valor_nao_financiavel' => :'compoeOfertaValorNaoFinanciavel',
        
        :'compoe_oferta_valor_novos_lancamentos' => :'compoeOfertaValorNovosLancamentos',
        
        :'recalcula_parcelamento_para_entrada_maior' => :'recalculaParcelamentoParaEntradaMaior',
        
        :'minimo_parcelas_recalculo_parcelamento' => :'minimoParcelasRecalculoParcelamento',
        
        :'recalcula_parcelamento' => :'recalculaParcelamento',
        
        :'numero_minimo_ofertas' => :'numeroMinimoOfertas',
        
        :'aceita_pagamento_maior_que_entrada' => :'aceitaPagamentoMaiorQueEntrada',
        
        :'antecipa_parcelamentos_abertos' => :'antecipaParcelamentosAbertos',
        
        :'valor_minimo_parcela' => :'valorMinimoParcela',
        
        :'percentual_limitar_valor_minimo_parcela' => :'percentualLimitarValorMinimoParcela',
        
        :'id_regra_campanha' => :'idRegraCampanha',
        
        :'parcelar_apenas_minimo' => :'parcelarApenasMinimo',
        
        :'usuario' => :'usuario'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        
        :'id' => :'Integer',
        
        :'id_produto' => :'Integer',
        
        :'compoe_oferta_valor_rotativo' => :'BOOLEAN',
        
        :'compoe_oferta_valor_nao_financiavel' => :'BOOLEAN',
        
        :'compoe_oferta_valor_novos_lancamentos' => :'BOOLEAN',
        
        :'recalcula_parcelamento_para_entrada_maior' => :'BOOLEAN',
        
        :'minimo_parcelas_recalculo_parcelamento' => :'BOOLEAN',
        
        :'recalcula_parcelamento' => :'BOOLEAN',
        
        :'numero_minimo_ofertas' => :'BOOLEAN',
        
        :'aceita_pagamento_maior_que_entrada' => :'BOOLEAN',
        
        :'antecipa_parcelamentos_abertos' => :'BOOLEAN',
        
        :'valor_minimo_parcela' => :'Float',
        
        :'percentual_limitar_valor_minimo_parcela' => :'Float',
        
        :'id_regra_campanha' => :'Integer',
        
        :'parcelar_apenas_minimo' => :'BOOLEAN',
        
        :'usuario' => :'String'
        
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      
      if attributes[:'id']
        
        
        self.id = attributes[:'id']
        
      
      end

      
      if attributes[:'idProduto']
        
        
        self.id_produto = attributes[:'idProduto']
        
      
      end

      
      if attributes[:'compoeOfertaValorRotativo']
        
        
        self.compoe_oferta_valor_rotativo = attributes[:'compoeOfertaValorRotativo']
        
      
      end

      
      if attributes[:'compoeOfertaValorNaoFinanciavel']
        
        
        self.compoe_oferta_valor_nao_financiavel = attributes[:'compoeOfertaValorNaoFinanciavel']
        
      
      end

      
      if attributes[:'compoeOfertaValorNovosLancamentos']
        
        
        self.compoe_oferta_valor_novos_lancamentos = attributes[:'compoeOfertaValorNovosLancamentos']
        
      
      end

      
      if attributes[:'recalculaParcelamentoParaEntradaMaior']
        
        
        self.recalcula_parcelamento_para_entrada_maior = attributes[:'recalculaParcelamentoParaEntradaMaior']
        
      
      end

      
      if attributes[:'minimoParcelasRecalculoParcelamento']
        
        
        self.minimo_parcelas_recalculo_parcelamento = attributes[:'minimoParcelasRecalculoParcelamento']
        
      
      end

      
      if attributes[:'recalculaParcelamento']
        
        
        self.recalcula_parcelamento = attributes[:'recalculaParcelamento']
        
      
      end

      
      if attributes[:'numeroMinimoOfertas']
        
        
        self.numero_minimo_ofertas = attributes[:'numeroMinimoOfertas']
        
      
      end

      
      if attributes[:'aceitaPagamentoMaiorQueEntrada']
        
        
        self.aceita_pagamento_maior_que_entrada = attributes[:'aceitaPagamentoMaiorQueEntrada']
        
      
      end

      
      if attributes[:'antecipaParcelamentosAbertos']
        
        
        self.antecipa_parcelamentos_abertos = attributes[:'antecipaParcelamentosAbertos']
        
      
      end

      
      if attributes[:'valorMinimoParcela']
        
        
        self.valor_minimo_parcela = attributes[:'valorMinimoParcela']
        
      
      end

      
      if attributes[:'percentualLimitarValorMinimoParcela']
        
        
        self.percentual_limitar_valor_minimo_parcela = attributes[:'percentualLimitarValorMinimoParcela']
        
      
      end

      
      if attributes[:'idRegraCampanha']
        
        
        self.id_regra_campanha = attributes[:'idRegraCampanha']
        
      
      end

      
      if attributes[:'parcelarApenasMinimo']
        
        
        self.parcelar_apenas_minimo = attributes[:'parcelarApenasMinimo']
        
      
      end

      
      if attributes[:'usuario']
        
        
        self.usuario = attributes[:'usuario']
        
      
      end

      
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      
      
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
    end

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared 
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          id_produto == o.id_produto &&
          compoe_oferta_valor_rotativo == o.compoe_oferta_valor_rotativo &&
          compoe_oferta_valor_nao_financiavel == o.compoe_oferta_valor_nao_financiavel &&
          compoe_oferta_valor_novos_lancamentos == o.compoe_oferta_valor_novos_lancamentos &&
          recalcula_parcelamento_para_entrada_maior == o.recalcula_parcelamento_para_entrada_maior &&
          minimo_parcelas_recalculo_parcelamento == o.minimo_parcelas_recalculo_parcelamento &&
          recalcula_parcelamento == o.recalcula_parcelamento &&
          numero_minimo_ofertas == o.numero_minimo_ofertas &&
          aceita_pagamento_maior_que_entrada == o.aceita_pagamento_maior_que_entrada &&
          antecipa_parcelamentos_abertos == o.antecipa_parcelamentos_abertos &&
          valor_minimo_parcela == o.valor_minimo_parcela &&
          percentual_limitar_valor_minimo_parcela == o.percentual_limitar_valor_minimo_parcela &&
          id_regra_campanha == o.id_regra_campanha &&
          parcelar_apenas_minimo == o.parcelar_apenas_minimo &&
          usuario == o.usuario
    end

    # @see the `==` method
    # @param [Object] Object to be compared 
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, id_produto, compoe_oferta_valor_rotativo, compoe_oferta_valor_nao_financiavel, compoe_oferta_valor_novos_lancamentos, recalcula_parcelamento_para_entrada_maior, minimo_parcelas_recalculo_parcelamento, recalcula_parcelamento, numero_minimo_ofertas, aceita_pagamento_maior_que_entrada, antecipa_parcelamentos_abertos, valor_minimo_parcela, percentual_limitar_valor_minimo_parcela, id_regra_campanha, parcelar_apenas_minimo, usuario].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Pier.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value 
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end


end
