=begin
PIER Labs


Gest\u00C3\u00A3o de pagamento eletr\u00C3\u00B4nicos como servi\u00C3\u00A7o


OpenAPI spec version: 0.0.1
Contact: pierlabs@conductor.com.br
Generated by: https://github.com/swagger-api/swagger-codegen.git


License: Apache 2.0
http://www.apache.org/licenses/LICENSE-2.0.html



Terms of Service: http://pierlabs.io/terms/


=end

require 'spec_helper'
require 'json'

# Unit tests for Pier::DocumentosApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DocumentosApi' do
  before do
    # run before each test
    @instance = Pier::DocumentosApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DocumentosApi' do
    it 'should create an instact of DocumentosApi' do
      @instance.should be_a(Pier::DocumentosApi)
    end
  end


  # unit tests for salvar_using_post5
  # Cadastra documentos
  # Esse recurso permite cadastrar documentos.
  # @param persist persist
  # @param [Hash] opts the optional parameters
  # @return [DocumentoResponse]
  describe 'salvar_using_post5 test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end


  # unit tests for salvar_using_post6
  # Cadastra os templates dos documentos
  # Esse recurso permite cadastrar templates dos documentos.
  # @param persist persist
  # @param [Hash] opts the optional parameters
  # @return [DocumentoTemplateResponse]
  describe 'salvar_using_post6 test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end


  # unit tests for salvar_using_post7
  # Cadastra os tipos de documentos
  # Esse recurso permite cadastrar tipos de documentos.
  # @param persist persist
  # @param [Hash] opts the optional parameters
  # @return [DocumentoTipoResponse]
  describe 'salvar_using_post7 test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end


end

