=begin
PIER Labs

Gest\u00C3\u00A3o de pagamento eletr\u00C3\u00B4nicos como servi\u00C3\u00A7o

OpenAPI spec version: 0.0.1
Contact: pierlabs@conductor.com.br
Generated by: https://github.com/swagger-api/swagger-codegen.git

License: Apache 2.0
http://www.apache.org/licenses/LICENSE-2.0.html

Terms of Service: http://pierlabs.io/terms/

=end

require 'spec_helper'
require 'json'

# Unit tests for Pier::EnderecoNacionalApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EnderecoNacionalApi' do
  before do
    # run before each test
    @instance = Pier::EnderecoNacionalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EnderecoNacionalApi' do
    it 'should create an instact of EnderecoNacionalApi' do
      @instance.should be_a(Pier::EnderecoNacionalApi)
    end
  end

  # unit tests for consultar_endereco_using_get
  # Consultar Endere\u00C3\u00A7o
  # Este recurso permite consultar endere\u00C3\u00A7os atrav\u00C3\u00A9s do CEP.
  # @param cep CEP
  # @param [Hash] opts the optional parameters
  # @return [EnderecoResponse]
  describe 'consultar_endereco_using_get test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
