=begin
PIER Labs


Gest\u00C3\u00A3o de pagamento eletr\u00C3\u00B4nicos como servi\u00C3\u00A7o


OpenAPI spec version: 0.0.1
Contact: pierlabs@conductor.com.br
Generated by: https://github.com/swagger-api/swagger-codegen.git


License: Apache 2.0
http://www.apache.org/licenses/LICENSE-2.0.html



Terms of Service: http://pierlabs.io/terms/


=end

require 'spec_helper'
require 'json'

# Unit tests for Pier::PermissaoPaisesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PermissaoPaisesApi' do
  before do
    # run before each test
    @instance = Pier::PermissaoPaisesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PermissaoPaisesApi' do
    it 'should create an instact of PermissaoPaisesApi' do
      @instance.should be_a(Pier::PermissaoPaisesApi)
    end
  end


  # unit tests for consultar_pais_using_get
  # Apresenta dados de um determinado pa\u00C3\u00ADs
  # Este m\u00C3\u00A9todo permite consultar dados de um determinado pa\u00C3\u00ADs a partir de seu codigo de identifica\u00C3\u00A7\u00C3\u00A3o (id).
  # @param id C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do pa\u00C3\u00ADs (id).
  # @param [Hash] opts the optional parameters
  # @return [PaisResponse]
  describe 'consultar_pais_using_get test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end


  # unit tests for listar_continentes_using_get
  # Lista os continentes
  # Este recurso permite listar os continentes utilizados no recurso de permiss\u00C3\u00A3o de uso do cart\u00C3\u00A3o no exterior
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'listar_continentes_using_get test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end


  # unit tests for listar_paises_using_get
  # Lista os pa\u00C3\u00ADses
  # Este recurso permite listar os pa\u00C3\u00ADses.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :sort Tipo de ordena\u00C3\u00A7\u00C3\u00A3o dos registros.
  # @option opts [Integer] :page P\u00C3\u00A1gina solicitada (Default = 0)
  # @option opts [Integer] :limit Limite de elementos por solicita\u00C3\u00A7\u00C3\u00A3o (Default = 50, Max = 50)
  # @option opts [String] :codigo C\u00C3\u00B3digo do pa\u00C3\u00ADs
  # @option opts [String] :sigla Sigla do pa\u00C3\u00ADs
  # @option opts [String] :descricao Nome do pa\u00C3\u00ADs
  # @option opts [String] :continente Continente no qual o pa\u00C3\u00ADs faz parte
  # @option opts [BOOLEAN] :flag_ativo Atributo que representa se o pa\u00C3\u00ADs est\u00C3\u00A1 ativo
  # @return [PagePaisResponse]
  describe 'listar_paises_using_get test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end


end

