=begin
PIER Labs

Gest\u00E3o de pagamento eletr\u00F4nicos como servi\u00E7o

OpenAPI spec version: 0.0.1
Contact: pierlabs@conductor.com.br
Generated by: https://github.com/swagger-api/swagger-codegen.git

License: Apache 2.0
http://www.apache.org/licenses/LICENSE-2.0.html

Terms of Service: http://pierlabs.io/terms/

=end

require 'spec_helper'
require 'json'

# Unit tests for Pier::ServicoContaApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ServicoContaApi' do
  before do
    # run before each test
    @instance = Pier::ServicoContaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServicoContaApi' do
    it 'should create an instact of ServicoContaApi' do
      @instance.should be_a(Pier::ServicoContaApi)
    end
  end

  # unit tests for ativar_anuidade_using_post
  # Atribuir Anuidade
  # Esse recurso permite configurar qual a regra de Anuidade que ser\u00E1 atribu\u00EDda a uma determinada Conta.
  # @param id C\u00F3digo de identifica\u00E7\u00E3o da conta (id).
  # @param id_anuidade Identificador da anuidade
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :sort Tipo de ordena\u00E7\u00E3o dos registros.
  # @option opts [Integer] :page P\u00E1gina solicitada (Default = 0)
  # @option opts [Integer] :limit Limite de elementos por solicita\u00E7\u00E3o (Default = 50, Max = 50)
  # @option opts [String] :ddd DDD do celular
  # @option opts [String] :celular N\u00FAmero do celular
  # @option opts [Integer] :id_operadora Identificador da operadora do celular
  # @option opts [Integer] :id_origem_comercial Identificador da origem comercial
  # @return [Object]
  describe 'ativar_anuidade_using_post test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for ativar_envio_fatura_email_using_post
  #  Ativa o servi\u00E7o de envio de fatura por email
  # Este recurso ativa o servi\u00E7o de envio de fatura por email
  # @param id C\u00F3digo de identifica\u00E7\u00E3o da conta (id).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'ativar_envio_fatura_email_using_post test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for desativar_envio_fatura_email_using_post
  # Desativa o servi\u00E7o de envio de fatura por email
  # Este recurso desativa o servi\u00E7o de envio de fatura por email
  # @param id C\u00F3digo de identifica\u00E7\u00E3o da conta (id).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'desativar_envio_fatura_email_using_post test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for listar_anuidades_using_get
  # Listar Anuidades
  # Lista as anuidades
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :sort Tipo de ordena\u00E7\u00E3o dos registros.
  # @option opts [Integer] :page P\u00E1gina solicitada (Default = 0)
  # @option opts [Integer] :limit Limite de elementos por solicita\u00E7\u00E3o (Default = 50, Max = 50)
  # @return [PageAnuidadeResponse]
  describe 'listar_anuidades_using_get test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for listar_operadoras_telefonicas_using_get
  # Listar Operadoras
  # Lista as operadoras.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :sort Tipo de ordena\u00E7\u00E3o dos registros.
  # @option opts [Integer] :page P\u00E1gina solicitada (Default = 0)
  # @option opts [Integer] :limit Limite de elementos por solicita\u00E7\u00E3o (Default = 50, Max = 50)
  # @return [PageOperadoraResponse]
  describe 'listar_operadoras_telefonicas_using_get test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
